### ISSUE TITLE
What is requirements?

### ISSUE THREAD

**Issue by bushev** [mixalbl4-127/xinput-mouse-key-logger#1]
Hello! Awesome project 👍  I'm looking to solution to help me to build cross platform (Win, Linux, macOS) [activity-logger](https://github.com/bushev/activity-logger).

You module is for Windows only? Which version are supported?

**Comment by mk-pmb** [comment]
As far as I can see, the only requirement of this project is that you have a global command `xinput` installed that acts like [xinput for Linux](https://linux.die.net/man/1/xinput) does.

**Comment by mixalbl4-127** [comment]
@mk-pmb is right, this module for Linux with xinput
