### ISSUE TITLE
Live mode reports no data for keyboards

### ISSUE THREAD

**Issue by mk-pmb** [mixalbl4-127/xinput-mouse-key-logger#2]
… because `xinput --test` doesn't. Fast polling with `--query-state` works, however. Maybe you want to add a warning and/or workaround?

Ubuntu 14.04.5 LTS trusty
xinput version 1.6.1
XI version on server: 2.3

**Comment by mixalbl4-127** [comment]
Hm, why `xinput --test' doesn`t work? Do you have logs with errors?
And simple change `--test` to `--query-state` is works for you?

**Comment by mk-pmb** [comment]
Back then I had to capture the output of `--query-state` repeatedly and compare it to the previous capture to find what has changed. The logs would have been empty files because `xinput --test` didn't react to keys being pressed or released, using the same device number for which `--query-state` reported the correct key states. Today I tried just `--test` again and it worked out of the box. I have no idea what went wrong back then.
